### ISSUE TITLE
Cauldron permission bug?

### ISSUE THREAD

**Issue by Telemain** [elix-x/Teleplates#1]
Right click portal with stick works, but unable to select friends to give permissions to.
Additionally said friends were able to enter portal, but had no destination options effectively trapping them.

**Comment by elix-x** [comment]
Have you permissions options enabled in config? Did you right clicked or left clicked your friends? What it was printing to you in chat? When you right clicked teleplate? Left clicked friends? Is it lan server or dedicated server?

Oh, and i will fix bug where you can enter 5th dimension if you don't have teleplates... Maybe...
As alternative, instead of fixing it, i might just do so it kills you...
Anyways, trapping inside 5th dimension if no exit present is kinda logical, but kinda bad...

**Comment by Telemain** [comment]
Permissions were enabled. Neither right clicking not left clicking seemed
to do anything. Text showed up in chat when clicking the plate.

It was something like
"Click a player to cycle through permissions"
And
"Permissions saved"
Only those two

Dedicated kcauldron server.

Thank you for helping me with this

**Comment by elix-x** [comment]
Were those 2 messages printed in a row, when you right clicked once?
Or you clicked the telepate twice?
How much sticks were you holding?

**Comment by Telemain** [comment]
Two clicks. Also, whether or not I had left/right clicked a player in
between, it played those two messages. I held one stick.

As a side note, the stick did no damage when in permissions selecting mode.

**Comment by elix-x** [comment]
So you right clicked once and it printed both messages?
If yes, that's a bug and should be fixed.
If no, you should do this:
Right click teleplate.
Left click fried.
Right click teleplate.

**Comment by Telemain** [comment]
Did that. Message printed only when right clicking plate. Not when clicking
friend. Friend was unable to use plate even though i clicked them.

**Comment by elix-x** [comment]
Now, when you left click your friend, message saying "dude101 is now user" should be printed in chat.
Also (kinda sorry for my not complete understanding), please write what you did and what chat did, like this:
1) Me: telplate. Chat: no
2) Me: teleplate Chat: yes

**Comment by Telemain** [comment]
Not at all. Thanks for helping me use your amazing mod.

1) Right click teleplate with stick.
2) Chat says to hit players with stick.
3) Left click friend with stick. Nothing happens though strangely they
don't take damage.
4) Right click teleplate.
5) Chat says that permissions have been saved.
6) Friend uses plate but gets stuck with no destinations.

**Comment by elix-x** [comment]
Thaks! It cleared for me a lot of code searching! The fact that your friend takes no damage makes it even weirder - it means that it succesfully completes all steps of saving data to stick... (taking no damage in this case is intended)... I'll see what's wrong...

**Comment by elix-x** [comment]
Ok, i'm dumb... I forgot to add "save player to stick" line... 1.0.2 incoming!!!

**Comment by elix-x** [comment]
1.0.2 is up.

**Comment by Telemain** [comment]
Thanks a bunch!
