### ISSUE TITLE
Same Location Bug

### ISSUE THREAD

**Issue by MokahTGS** [elix-x/Teleplates#2]
So there's a major bug if you pick the same location that you are coming from, it will destroy the plate. 

Also, in picking up the teleplate, it gets destroyed.  Not sure if that is by design, but its annoying.

**Comment by elix-x** [comment]
1) I'll see what's wrong and fix it.
2) What exactly do you mean?

**Comment by elix-x** [comment]
So, i tested and it seems that i cannot reproduce first bug. Please:
First, check that your are using latest version.
Second, if latest version does not solves it, tell me what exactly you did for this to happen and how often this happens...

**Comment by MokahTGS** [comment]
I'll test again tonight but the exact steps were:

1) Look down and enter the 5th dimension.
2) Choose the location where you already are.  Example: You are at a location called "Home" and you choose "Home" from the list.
3) Arrive at same location and the Teleplate gets destroyed.

**Comment by elix-x** [comment]
Ok, that's interesting... And unexplainable... Again, please, try again with latest version...
