### ISSUE TITLE
[1.7.10] Crash

### ISSUE THREAD

**Issue by tanto259** [elix-x/Teleplates#20]
Crash when starting minecraft.
Crash log: [http://pastebin.com/Af2Ma9b7](http://pastebin.com/Af2Ma9b7)

**Comment by Elix-x** [comment]
Check your config file. Go to fluid consomation mode and change fluid to consume to "LAVA".

**Comment by tanto259** [comment]
I changed the fluidToConsume=LAVA , but unfortunately it still crashed.
Crash Report: [http://pastebin.com/XYwY4fXu](http://pastebin.com/XYwY4fXu)
Config File: [http://pastebin.com/hnEK7ykd](http://pastebin.com/hnEK7ykd)

**Comment by Elix-x** [comment]
Try deleting whole consomation-fluid block.

**Comment by tanto259** [comment]
Unfortunately, the consomation-fluid block is recreated when starting minecraft. Then the game crashes again.
Crash log: [http://pastebin.com/PEsqW4Yb](http://pastebin.com/PEsqW4Yb)

**Comment by Elix-x** [comment]
I know that is recreated each time you launch your game, but i don't know why it can't find fluids. Try changin fluidToConsume to WATER and if that does not work, it could only be another mod that breaks fluid registry.
So, if "fluidToConsume=WATER" does not work, than try removing all mods except excore and teleplates, deleting teleplates' config file and launching game.

**Comment by tanto259** [comment]
First, thank you for the fast reply. I just discovered that changing the "fluidToConsume=lava" (with all lowercase letter) works, while changing it to LAVA or WATER (with uppercase letter) doesn't work. Thanks for the help.

**Comment by Elix-x** [comment]
I guess something changed in fluid registry.
Good to know that it's fixed and how to fix it from now on.
