### ISSUE TITLE
java 7

### ISSUE THREAD

**Issue by SvEgiiVEteR** [elix-x/Teleplates#7]
http://hastebin.com/pejafufuge.md
1.2 and 1.2.1

**Comment by elix-x** [comment]
Are you sure this is cause by Teleplates?
If it does, you should be able to reproduce this crash with only Teleplates and Excore installed.

**Comment by SvEgiiVEteR** [comment]
Well .... I know that if you set your two mod the crash occurs 100 percent.
I tried several times.
..... try with your current 2 modes ...
I think the problem in java 7

**Comment by SvEgiiVEteR** [comment]
http://hastebin.com/asipuzevoh.js

**Comment by elix-x** [comment]
Ok. Thank you. I'll see where i'm using Function class.

**Comment by elix-x** [comment]
I think it has something to do with Excore packets.
Can't you use java 8???
Although, i'll find and fix this.
